### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by inkel** [magoyette/prometheus-rules-mode#1]
First of all: thank you!

I was wondering what's the status of this mode, are you planning on continue developing it?

**Comment by magoyette** [comment]
I haven't used Prometheus recently, so prometheus-rules-mode didn't get much attention. I wrote that mode to learn Emacs Lisp after I found no Emacs packages for Prometheus rules. 

If you find any missing features or bugs, feel free to open new issues. Pull requests are also welcome.

A few tasks would need to be done before prometheus-rules-mode can be added on Melpa:
- remove the dependency on company, since the completion is very basic and doesn't really require company
- add a build
- add some tests
- finding what is the minimum Emacs version that is required
- more manual testing, especially with the promtool integration. Some errors might have a format that the Flycheck checker won't handle properly.

Formatting is also missing, but I would keep that feature for later, since it will require more efforts and appears less essential to me.

Most of my efforts are currently on a different major mode, but I'll need to do many similar tasks for that other mode. So I'll probably come back to prometheus-rules-mode to put it in a releasable state. At my current pace, I expect the mode to be on Melpa before the end of 2017.

**Comment by inkel** [comment]
@magoyette thank you so much for a detailed answer!

**Comment by magoyette** [comment]
I was going to restart development on prometheus-rules-mode, but I noticed that Prometheus 2.0 changed the format of the rules to YAML: https://prometheus.io/docs/prometheus/latest/migration/#recording-rules-and-alerts

I'm archiving this repository on GitHub since I don't think I'll work with Prometheus 1.0 anymore.

**Comment by inkel** [comment]
That makes total sense. Thanks for answering anyway! That's so nice of you to do.

**Comment by magoyette** [comment]
This repository wasn't archived, but I'm now archiving it since Prometheus 2.0 was released at the end of 2017.
